# Numpy

### NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

### Advantage of using numpy over list:

- It consumes less memroy.
- Fast computation of numpy array.
- Numpy is convenient to use.

In [1]:
import numpy as np

## Creating Arrays from Python List

In [2]:
n = [1,2,3]
np.array(n)

array([1, 2, 3])

## Task 1
Create a numpy array from 2d list

In [3]:
#Solution

## Creating Arrays from Scratch

In [4]:
# Create a lenght-10 integer array filled with zeros.
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Create a 3 * 5 floating-point arrray filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create a 3*5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((2, 2))

array([[0.51464266, 0.73597026],
       [0.30557953, 0.95788295]])

In [11]:
#(pseudo-)random numbers work by starting with a number (the seed)
np.random.seed(0)

In [12]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

## Task 2
Create a 1d numpy array that contains first 10 multiple of 3

In [13]:
# Solution
           

## Numpy array attributes

In [14]:
x = np.random.randint(10, size=(3,4)) # Two-dimensional array
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("dtype: ", x.dtype)
print("itemsize: ", x.itemsize, "bytes")
print("nbytes: ", x.nbytes, "bytes")

x ndim:  2
x shape:  (3, 4)
x size:  12
dtype:  int64
itemsize:  8 bytes
nbytes:  96 bytes


## Array Indexing

In [15]:
x = np.random.randint(10, size=6)
x

array([9, 8, 9, 4, 3, 0])

In [16]:
x[1]

8

In [17]:
x[-2]

3

In [18]:
x = np.random.randint(10, size=(3,3))
x

array([[3, 5, 0],
       [2, 3, 8],
       [1, 3, 3]])

In [19]:
x[0,0]

3

In [20]:
x[1,-1]

8

In [21]:
# you can also modify values using any of the above index notation:
x[0,0] = 100
x

array([[100,   5,   0],
       [  2,   3,   8],
       [  1,   3,   3]])

## Task 3
Create a 1d numpy array of size 15 with values ranging from 10 to 49 but tenth value is -1. 

In [22]:
#Solution

## Array Slicing

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#first five element
x[:5]


array([0, 1, 2, 3, 4])

In [25]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [26]:
# middel subarray
x[4:7]

array([4, 5, 6])

In [27]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [28]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [29]:
x = np.random.randint(10, size=(3,3))
x

array([[3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]])

In [30]:
# two rows, three columns
x[:2, :3]

array([[3, 7, 0],
       [1, 9, 9]])

In [31]:
# first column of x
x[:, 0]

array([3, 1, 0])

## Task 4
Find the last row of 2d list x

In [75]:
# Solution


## Array Reshaping

In [33]:
x = np.arange(1, 10)
print("shape: ", x.shape)
x

shape:  (9,)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
y = x.reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
#turn an array into a one-dimensional representation
y.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Array Concatenation

In [36]:
x = np.array([1, 2, 3])
y = np.array([4, 3, 6])
np.concatenate([x,y])

array([1, 2, 3, 4, 3, 6])

## Vectorized operation

In [37]:
x = np.arange(1, 4)
x




array([1, 2, 3])

In [38]:
print(x + 2)
print(np.add(x,2))

[3 4 5]
[3 4 5]


In [39]:
print(x * 2)
print(np.multiply(x, 2))

[2 4 6]
[2 4 6]


In [40]:
print(-x)
print(np.negative(x))

[-1 -2 -3]
[-1 -2 -3]


In [41]:
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [42]:
np.sin(x)

array([-0.90929743, -0.84147098,  0.        ,  0.84147098,  0.90929743])

In [43]:
np.exp(x)

array([0.13533528, 0.36787944, 1.        , 2.71828183, 7.3890561 ])

In [44]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [45]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [46]:
np.sum(x)

10

In [47]:
np.min(x)

1

In [48]:
np.max(x)

4

In [49]:
np.mean(x)

2.5

In [50]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [51]:
# columns (first dimension)
np.sum(x, axis=0)

array([4, 6])

# Task 5
Find the sum of x across row

In [52]:
# Solution

## Working with Boolean Arrays

In [53]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [55]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [56]:
# how many values less than 6?
np.count_nonzero(x < 6)

6

## Boolean Arrays as Masks

In [57]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [59]:
# Select the element from x whole value is less than 5
x[ x < 5]
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Task 6
Find the element of x that is exactly divisible by 2.

In [60]:
# Solution

## Array Sorting


In [61]:
x = np.array([2, 1, 4, 3, 5])
x

array([2, 1, 4, 3, 5])

In [62]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [63]:
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [64]:
# sort each column of x
np.sort(x, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

# Task 7
Sort each row of x in ascending order.

In [65]:
# Solution

## Matrix Manipulation

In [66]:
a = np.array([[1,0],[0,1]])
a

array([[1, 0],
       [0, 1]])

In [67]:
b = np.array([[4,1],[2,2]])
b

array([[4, 1],
       [2, 2]])

In [68]:
c = np.matmul(a,b)
c

array([[4, 1],
       [2, 2]])

In [69]:
np.linalg.det(c)

6.0

In [70]:
np.linalg.inv(c) 

array([[ 0.33333333, -0.16666667],
       [-0.33333333,  0.66666667]])

## Dot Product

In [71]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 0, 1])

In [72]:
np.dot(a,b)


5

In [73]:
a = np.array([[1,0],[0,1]])
b = np.array([[4,1],[2,2]])
np.dot(a,b)

array([[4, 1],
       [2, 2]])

# Task 8

Let X is 3 * 3 matrix

y is 3 * 1 matrix

$ theta = (X^TX)^{-1}X^Ty $

In [74]:
#Solution