# Numpy

### NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

### Advantage of using numpy over list:

- It consumes less memroy.
- Fast computation of numpy array.
- Numpy is convenient to use.

In [1]:
import numpy as np

## Creating Arrays from Python List

In [2]:
n = [1,2,3]
np.array(n)

array([1, 2, 3])

## Creating Arrays from Scratch

In [3]:
# Create a lenght-10 integer array filled with zeros.
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# Create a 3 * 5 floating-point arrray filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# Create a 3*5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((2, 2))

array([[0.86158226, 0.05590577],
       [0.3412903 , 0.09224585]])

In [75]:
#(pseudo-)random numbers work by starting with a number (the seed)
np.random.seed(0)

In [76]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

## Numpy array attributes

In [77]:
x = np.random.randint(10, size=(3,4)) # Two-dimensional array
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("dtype: ", x.dtype)
print("itemsize: ", x.itemsize, "bytes")
print("nbytes: ", x.nbytes, "bytes")

x ndim:  2
x shape:  (3, 4)
x size:  12
dtype:  int64
itemsize:  8 bytes
nbytes:  96 bytes


## Array Indexing

In [185]:
x = np.random.randint(10, size=6)
x

array([2, 0, 3, 5, 9, 4])

In [186]:
x[1]

0

In [187]:
x[-2]

9

In [188]:
x = np.random.randint(10, size=(3,3))
x

array([[4, 6, 4],
       [4, 3, 4],
       [4, 8, 4]])

In [189]:
x[0,0]

4

In [190]:
x[1,-1]

4

In [191]:
# you can also modify values using any of the above index notation:
x[0,0] = 100
x

array([[100,   6,   4],
       [  4,   3,   4],
       [  4,   8,   4]])

## Array Slicing

In [89]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
#first five element
x[:5]


array([0, 1, 2, 3, 4])

In [93]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [94]:
# middel subarray
x[4:7]

array([4, 5, 6])

In [95]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [96]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [101]:
x = np.random.randint(10, size=(3,3))
x

array([[6, 8, 4],
       [1, 4, 9],
       [8, 1, 1]])

In [102]:
# two rows, three columns
x[:2, :3]

array([[6, 8, 4],
       [1, 4, 9]])

In [103]:
# first column of x
x[:, 0]

array([6, 1, 8])

In [107]:
# last row of x
x[-1, :]

array([8, 1, 1])

## Array Reshaping

In [113]:
x = np.arange(1, 10)
print("shape: ", x.shape)
x

shape:  (9,)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
y = x.reshape(3,3)
y

array([[100,   6,   4],
       [  4,   3,   4],
       [  4,   8,   4]])

In [201]:
#turn an array into a one-dimensional representation
y.ravel()

array([100,   6,   4,   4,   3,   4,   4,   8,   4])

## Array Concatenation

In [120]:
x = np.array([1, 2, 3])
y = np.array([4, 3, 6])
np.concatenate([x,y])

array([1, 2, 3, 4, 3, 6])

## Vectorized operation

In [127]:
x = np.arange(1, 4)
x




array([1, 2, 3])

In [130]:
print(x + 2)
print(np.add(x,2))

[3 4 5]
[3 4 5]


In [132]:
print(x * 2)
print(np.multiply(x, 2))

[2 4 6]
[2 4 6]


In [133]:
print(-x)
print(np.negative(x))

[-1 -2 -3]
[-1 -2 -3]


In [142]:
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [143]:
np.sin(x)

array([-0.90929743, -0.84147098,  0.        ,  0.84147098,  0.90929743])

In [144]:
np.exp(x)

array([0.13533528, 0.36787944, 1.        , 2.71828183, 7.3890561 ])

In [149]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [150]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [151]:
np.sum(x)

10

In [152]:
np.min(x)

1

In [153]:
np.max(x)

4

In [202]:
np.mean(x)

15.222222222222221

In [206]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [208]:
# columns (first dimension)
np.sum(x, axis=0)

array([4, 6])

In [209]:
# rows (second dimension)
np.sum(x, axis=1)

array([3, 7])

## Working with Boolean Arrays

In [157]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [159]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [160]:
# how many values less than 6?
np.count_nonzero(x < 6)

6

## Boolean Arrays as Masks

In [163]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [167]:
# Select the element from x whole value is less than 5
x[ x < 5]

array([0, 1, 2, 3, 4])

## Array Sorting


In [172]:
x = np.array([2, 1, 4, 3, 5])
x

array([2, 1, 4, 3, 5])

In [173]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [179]:
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [178]:
# sort each column of x
np.sort(x, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [181]:
# sort each column of x
np.sort(x, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Matrix Manipulation

In [232]:
a = np.array([[1,0],[0,1]])
a

array([[1, 0],
       [0, 1]])

In [234]:
b = np.array([[4,1],[2,2]])
b

array([[4, 1],
       [2, 2]])

In [236]:
c = np.matmul(a,b)
c

array([[4, 1],
       [2, 2]])

In [237]:
np.linalg.det(c)

6.0

In [238]:
np.linalg.inv(c) 

array([[ 0.33333333, -0.16666667],
       [-0.33333333,  0.66666667]])

## Dot Product

In [240]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 0, 1])

In [243]:
np.dot(a,b)


5

In [244]:
a = np.array([[1,0],[0,1]])
b = np.array([[4,1],[2,2]])
np.dot(a,b)

array([[4, 1],
       [2, 2]])